name = "2k-e-recruitment"
main = ".open-next/worker.js"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "2k-e-recruitment-db"
database_id = "f60db6ae-83e8-42e2-ba74-d13f4f0490ef"
migrations_dir = "drizzle"
