CREATE TABLE `applicant_references` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`application_id` integer NOT NULL,
	`name` text NOT NULL,
	`address` text,
	`phone` text,
	`occupation` text,
	FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `applications` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`status` text DEFAULT 'submitted' NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`nickname` text,
	`position_applied_1` text NOT NULL,
	`position_applied_2` text,
	`available_start_date` text,
	`expected_salary` real,
	`address_no` text,
	`moo` text,
	`road` text,
	`sub_district` text,
	`district` text,
	`province` text,
	`postal_code` text,
	`phone` text,
	`mobile` text NOT NULL,
	`line_id` text,
	`email` text NOT NULL,
	`social_media` text,
	`living_with` text,
	`date_of_birth` text NOT NULL,
	`age` integer,
	`chinese_zodiac` text,
	`race` text,
	`nationality` text,
	`religion` text,
	`id_card_number` text NOT NULL,
	`id_card_expiry` text,
	`height_cm` real,
	`weight_kg` real,
	`military_status` text,
	`marital_status` text,
	`sex` text,
	`ever_practiced_dharma` integer DEFAULT false,
	`dharma_place` text,
	`dharma_duration` text,
	`doc_id_card` integer DEFAULT false,
	`doc_house_registration` integer DEFAULT false,
	`doc_passport` integer DEFAULT false,
	`doc_education_cert` integer DEFAULT false,
	`doc_work_cert` integer DEFAULT false,
	`doc_other` text,
	`father_name` text,
	`father_age` integer,
	`father_occupation` text,
	`mother_name` text,
	`mother_age` integer,
	`mother_occupation` text,
	`spouse_name` text,
	`spouse_workplace` text,
	`spouse_position` text,
	`number_of_children` integer DEFAULT 0,
	`number_of_siblings` integer,
	`number_of_brothers` integer,
	`number_of_sisters` integer,
	`child_order` integer,
	`typing_speed_thai` integer,
	`typing_speed_english` integer,
	`touch_typing` integer DEFAULT false,
	`computer_skills` integer DEFAULT false,
	`computer_skills_detail` text,
	`car_driver` integer DEFAULT false,
	`has_own_car` integer DEFAULT false,
	`car_license_no` text,
	`motorcycle_driver` integer DEFAULT false,
	`has_own_motorcycle` integer DEFAULT false,
	`motorcycle_license_no` text,
	`office_machine_skills` text,
	`hobbies` text,
	`can_work_up_country` integer DEFAULT false,
	`can_work_up_country_other` text,
	`emergency_contact_name` text,
	`emergency_contact_relation` text,
	`emergency_contact_address` text,
	`emergency_contact_phone` text,
	`info_source` text,
	`info_source_detail` text,
	`serious_illness` integer DEFAULT false,
	`illness_detail` text,
	`applied_before` integer DEFAULT false,
	`applied_before_when` text,
	`relatives_in_company` text,
	`self_introduction` text,
	`org_chart_description` text,
	`job_responsibilities` text,
	`signature_data_url` text,
	`signed_date` text
);
--> statement-breakpoint
CREATE TABLE `education` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`application_id` integer NOT NULL,
	`level` text NOT NULL,
	`institution` text,
	`major` text,
	`year_from` text,
	`year_to` text,
	`gpa` real,
	FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `language_skills` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`application_id` integer NOT NULL,
	`language` text NOT NULL,
	`language_other` text,
	`listening` text,
	`reading` text,
	`writing` text,
	FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `siblings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`application_id` integer NOT NULL,
	`name` text NOT NULL,
	`age` integer,
	`occupation` text,
	FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `trainings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`application_id` integer NOT NULL,
	`institution` text NOT NULL,
	`course` text,
	`date_from` text,
	`date_to` text,
	`has_certificate` integer DEFAULT false,
	FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `work_experience` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`application_id` integer NOT NULL,
	`company` text NOT NULL,
	`date_from` text,
	`date_to` text,
	`position` text,
	`job_description` text,
	`salary` real,
	`reason_for_leaving` text,
	FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON UPDATE no action ON DELETE cascade
);
